/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
  referenceImplementationsSidebar: [
    { type: 'autogenerated', dirName: 'reference-implementations' },
  ],
};

module.exports = sidebars;
