# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.

# pylint - sphinx doesn't use UPPER_CASE naming style for constants
# pylint: disable=invalid-name
# Some configurations are longer than 80 characters
# pylint: disable=line-too-long

import os
import sys
import pathlib
import glob
import re
import shutil

project = "Robotics AI Suite Documentation"

copyright = "2026, Intel Corporation"  # pylint: disable=redefined-builtin
author = "Intel Corporation"

version = "dev"
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# strict mode - all warnings are errors
warning_is_error = True

# extensions
extensions = [
    #    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_favicon",
    "sphinx_sitemap",
    "sphinx_togglebutton",
    "sphinxcontrib.asciinema",
    #    "sphinxcontrib.images",
    "sphinxcontrib.jquery",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.openapi",
    "sphinxcontrib.spelling",
    "sphinxcontrib.video",
    "myst_parser",
]

templates_path = ["_templates"]

# exclude these files from processing
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "README.md",
]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# text encoding
source_encoding = "UTF-8"

# The language for content autogenerated by Sphinx.
language = "en"

# The master toctree document (entry point)
master_doc = "index"

# rst_epilog, added to the end of every rst doc
# include substituions in base directory
rst_epilog = """
.. include:: /substitutions.txt
"""

# Create empty dictionary
myst_substitutions = {}

# config for autosectionlabel
# see: https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 3

spelling_filters = ["sphinxcontrib.spelling.filters.ContractionFilter"]

spelling_exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_title = "Robotics AI Suite Documentation"
html_theme = "pydata_sphinx_theme"

html_context = {
    "default_mode": "dark",
}

html_theme_options = {
    "navigation_depth": 6,
    "show_toc_level": 1,
    "show_nav_level": 1,
    # "collapse_navigation": False,
    # "navigation_with_keys": True,
    # Navbar Configuration
    # "navbar_start": [],  # Logo on the left
    # Custom links (see _templates/navbar-links.html) mirroring the Docusaurus navbar.
    "navbar_center": ["navbar-links"],
    # "navbar_end": ["search-field"],  # Search + Theme Switcher on the right
    "header_links_before_dropdown": 4,
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/open-edge-platform/robotics-ai-suite",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        }
    ],
    "logo": {
        "text": "Robotics AI Suite",
        "link": "/",
        # "image_dark": "_static/logo-dark.svg",
    },
    "show_prev_next": False,
}
# common theme options
html_baseurl = "https://docs.robotics.intel.com/"
html_favicon = "_static/logo.svg"
# html_show_sourcelink = True  # Show source link
html_show_sphinx = False  # Hide "Built with Sphinx"
html_static_path = ["_static"]
html_css_files = ["./css/customstyle.css", "./css/menu-position-rules.css"]

# Omit the language segment from sitemap URLs (default scheme is "{lang}{version}{link}")
sitemap_url_scheme = "{version}{link}"

# Dynamically add switcher content if switcher_data.txt exists
switcher_data_file = os.path.dirname(os.path.abspath(__file__)) + "/switcher_data.txt"
if os.path.isfile(switcher_data_file):
    with open(switcher_data_file) as file:
        lines = [line.rstrip() for line in file]
    # Switcher URL needs to exist prior to building, so hardcode now and replace later
    html_theme_options_append = {
        "switcher": {
            "json_url": "https://docs.openedgeplatform.intel.com/theme/switcher.json",
            "version_match": f"{lines[1].split()[0]}",
        },
        "navbar_start": ["navbar-logo", "version-switcher"],
    }
    html_theme_options.update(html_theme_options_append)

# Linkcheck options
linkcheck_timeout = 5
linkcheck_retries = 4
linkcheck_workers = 20  # Specify number of worker threads

linkcheck_ignore = [
    "https://www.intel.com/",
    "https://ark.intel.com/",
    "../static",  # ignore links to OpenAPI docs
    "localhost",
    "127.0.0.1",
]

# replacement user agent to avoid 403 errors
linkcheck_request_headers = {
    "*": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/134.0.0.0 Safari/537.36",
    }
}

linkcheck_exclude_documents = [
    "release_notes/containers_helm_charts*",
    "release_notes/third_party_components*",
]

myst_fence_as_directive = ["mermaid"]
myst_heading_anchors = 5
suppress_warnings = ["myst.xref_missing", "myst.domains"]
myst_enable_extensions = [
    "attrs_inline",
    "attrs_block",
    "substitution",
    "colon_fence",
    "alert",
]

# -- Functions for handling linkcheck ignore and substitutions lists ---------
# Allow appending to linkcheck_ignore
linkcheck_ignore_append = []
linkcheck_ignore_append_file = str(pathlib.Path.cwd()) + "/linkcheck_ignore_append.txt"
if os.path.isfile(linkcheck_ignore_append_file):
    with open(linkcheck_ignore_append_file, encoding="utf-8") as file:
        linkcheck_ignore_append = [line.strip() for line in file if line.strip()]


# -- Functions for uncommenting hidden directives in Markdown files ----------
def show_hidden_directives(app, config):  # pylint: disable=unused-argument
    """
    Remove custom html comment tags used to hide the Sphinx directives in .md files
    """
    found_file = 0
    mdocs = pathlib.Path(__file__).parent
    mdfiles = glob.iglob(os.path.join(mdocs, "*/**/*.md"), recursive=True)
    for md in mdfiles:
        if not os.path.isfile(md):
            continue
        try:
            with open(md, "r+", encoding="utf-8") as md_file:
                contents = md_file.read()
                if not re.search(r"<!--\s{0,2}hide.{0,2}directive", contents):
                    continue
                # Remove the "<!--hide_directive" comment tag that hides content in GitHub.
                for tag in re.findall(r"<!--\s{0,2}hide.{0,2}directive", contents):
                    contents = contents.replace(
                        tag, re.sub(r"<!--\s{0,2}hide.{0,2}directive", "", tag)
                    )
                # Remove the "hide_directive-->" comment tag that hides content in GitHub.
                for tag in re.findall(r"hide.{0,2}directive\s{0,2}-->", contents):
                    contents = contents.replace(
                        tag, re.sub(r"hide.{0,2}directive\s{0,2}-->", "", tag)
                    )
                md_file.seek(0)
                md_file.write(contents)
                md_file.truncate()
                found_file += 1
        except Exception:  # pylint: disable=broad-exception-caught
            pass
    print(f"Uncommented directives in {found_file} files", flush=True)


def filter_blueprints_sidebar(html_content):
    """
    Jinja filter: For pages under hardware_blueprints, filter the sidebar toctree
    so it only displays the Hardware Blueprints section.
    """
    from bs4 import BeautifulSoup
    from markupsafe import Markup

    is_soup = isinstance(html_content, BeautifulSoup)
    soup = html_content if is_soup else BeautifulSoup(str(html_content), "html.parser")

    current_keep = False
    elements_to_remove = []
    for child in list(soup.children):
        if child.name == "p" and "caption" in child.get("class", []):
            caption_text = child.get_text(strip=True)
            current_keep = "blueprint" in caption_text.lower()
        if not current_keep:
            elements_to_remove.append(child)
    for el in elements_to_remove:
        el.decompose()

    if is_soup:
        return soup
    return Markup(str(soup))


def filter_development_stack_sidebar(html_content):
    """
    Jinja filter: For development stack pages (outside hardware_blueprints),
    filter the sidebar toctree so it hides the Hardware Blueprints section.
    """
    from bs4 import BeautifulSoup
    from markupsafe import Markup

    is_soup = isinstance(html_content, BeautifulSoup)
    soup = html_content if is_soup else BeautifulSoup(str(html_content), "html.parser")

    current_keep = True
    elements_to_remove = []
    for child in list(soup.children):
        if child.name == "p" and "caption" in child.get("class", []):
            caption_text = child.get_text(strip=True)
            current_keep = "blueprint" not in caption_text.lower()
        if not current_keep:
            elements_to_remove.append(child)
    for el in elements_to_remove:
        el.decompose()

    if is_soup:
        return soup
    return Markup(str(soup))


def register_custom_jinja_filters(app):
    """
    Register custom filters with the Sphinx Jinja2 environment.
    """
    if hasattr(app.builder, "templates") and hasattr(app.builder.templates, "environment"):
        app.builder.templates.environment.filters["filter_blueprints_sidebar"] = (
            filter_blueprints_sidebar
        )
        app.builder.templates.environment.filters["filter_development_stack_sidebar"] = (
            filter_development_stack_sidebar
        )


# -- Function for setting up Sphinx extensions and event handlers ------------
def setup(app):
    """
    Sphinx entrypoint function
    """
    app.connect("config-inited", show_hidden_directives)
    app.connect("builder-inited", register_custom_jinja_filters)
